#############################################################################
# Makefile for building: csv_parser_gephi
# Generated by qmake (2.01a) (Qt 4.8.7) on: Wed Mar 1 10:37:29 2017
# Project:  csv_parser_gephi.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile csv_parser_gephi.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinclude -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		src/CsvOutput.cpp \
		src/DataInterface.cpp \
		src/MainDialog.cpp \
		src/PropertiesDialog.cpp moc_DataInterface.cpp \
		moc_MainDialog.cpp \
		moc_PropertiesDialog.cpp
OBJECTS       = main.o \
		CsvOutput.o \
		DataInterface.o \
		MainDialog.o \
		PropertiesDialog.o \
		moc_DataInterface.o \
		moc_MainDialog.o \
		moc_PropertiesDialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		csv_parser_gephi.pro
QMAKE_TARGET  = csv_parser_gephi
DESTDIR       = 
TARGET        = csv_parser_gephi

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: csv_parser_gephi.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile csv_parser_gephi.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile csv_parser_gephi.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/csv_parser_gephi1.0.0 || $(MKDIR) .tmp/csv_parser_gephi1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/csv_parser_gephi1.0.0/ && $(COPY_FILE) --parents include/CsvOutput.h include/DataInterface.h include/MainDialog.h include/PropertiesDialog.h .tmp/csv_parser_gephi1.0.0/ && $(COPY_FILE) --parents main.cpp src/CsvOutput.cpp src/DataInterface.cpp src/MainDialog.cpp src/PropertiesDialog.cpp .tmp/csv_parser_gephi1.0.0/ && (cd `dirname .tmp/csv_parser_gephi1.0.0` && $(TAR) csv_parser_gephi1.0.0.tar csv_parser_gephi1.0.0 && $(COMPRESS) csv_parser_gephi1.0.0.tar) && $(MOVE) `dirname .tmp/csv_parser_gephi1.0.0`/csv_parser_gephi1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/csv_parser_gephi1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_DataInterface.cpp moc_MainDialog.cpp moc_PropertiesDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_DataInterface.cpp moc_MainDialog.cpp moc_PropertiesDialog.cpp
moc_DataInterface.cpp: include/DataInterface.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/DataInterface.h -o moc_DataInterface.cpp

moc_MainDialog.cpp: include/PropertiesDialog.h \
		include/DataInterface.h \
		include/CsvOutput.h \
		include/MainDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/MainDialog.h -o moc_MainDialog.cpp

moc_PropertiesDialog.cpp: include/DataInterface.h \
		include/PropertiesDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/PropertiesDialog.h -o moc_PropertiesDialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp include/MainDialog.h \
		include/PropertiesDialog.h \
		include/DataInterface.h \
		include/CsvOutput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

CsvOutput.o: src/CsvOutput.cpp include/CsvOutput.h \
		include/DataInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CsvOutput.o src/CsvOutput.cpp

DataInterface.o: src/DataInterface.cpp include/DataInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataInterface.o src/DataInterface.cpp

MainDialog.o: src/MainDialog.cpp include/MainDialog.h \
		include/PropertiesDialog.h \
		include/DataInterface.h \
		include/CsvOutput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainDialog.o src/MainDialog.cpp

PropertiesDialog.o: src/PropertiesDialog.cpp include/PropertiesDialog.h \
		include/DataInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PropertiesDialog.o src/PropertiesDialog.cpp

moc_DataInterface.o: moc_DataInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DataInterface.o moc_DataInterface.cpp

moc_MainDialog.o: moc_MainDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainDialog.o moc_MainDialog.cpp

moc_PropertiesDialog.o: moc_PropertiesDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PropertiesDialog.o moc_PropertiesDialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

